/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutLaxyImport } from './routes/about.laxy'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AboutLaxyRoute = AboutLaxyImport.update({
  id: '/about/laxy',
  path: '/about/laxy',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about/laxy': {
      id: '/about/laxy'
      path: '/about/laxy'
      fullPath: '/about/laxy'
      preLoaderRoute: typeof AboutLaxyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about/laxy': typeof AboutLaxyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about/laxy': typeof AboutLaxyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about/laxy': typeof AboutLaxyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about/laxy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about/laxy'
  id: '__root__' | '/' | '/about/laxy'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLaxyRoute: typeof AboutLaxyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLaxyRoute: AboutLaxyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about/laxy"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about/laxy": {
      "filePath": "about.laxy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
